Attention: `py3dev` branch for Python 3 port
============================================

This content is is related to the `py3dev` branch
of the asciidoc github fork https://github.com/pepr/asciidoc.git

The fork and the branch was created explicitly for the development
of Python 3 port of the original https://github.com/asciidoc/asciidoc.
See the https://github.com/asciidoc/asciidoc/issues/83 for the beginning
of the effort.

Communication
-------------

Go to the https://github.com/pepr/asciidoc/issues[Issues]

The text below comes from the original.

[float]
AsciiDoc image:https://travis-ci.org/asciidoc/asciidoc.svg?branch=master[Build Status,link=https://travis-ci.org/asciidoc/asciidoc]
===================================================================================================================================

AsciiDoc is a text document format for writing notes, documentation,
articles, books, ebooks, slideshows, web pages, man pages and blogs.
AsciiDoc files can be translated to many formats including HTML, PDF,
EPUB, man page.

AsciiDoc is highly configurable: both the AsciiDoc source file syntax
and the backend output markups (which can be almost any type of
SGML/XML markup) can be customized and extended by the user.

Prerequisites
-------------
AsciiDoc is written in Python so you need a Python interpreter
(version 2.4 or later) to execute asciidoc(1). Python is installed by
default in most Linux distributions.  You can download Python from the
official Python website http://www.python.org.


Obtaining AsciiDoc
------------------
Documentation and installation instructions are on the AsciiDoc
website http://asciidoc.org/


Tools
-----
Current AsciiDoc version tested on Xubuntu Linux 10.04 with:

- Python 2.6.5
- DocBook XSL Stylesheets 1.76.1
- xsltproc (libxml 20706, libxslt 10126 and libexslt 815).
- w3m 0.5.2
- dblatex 0.3
- FOP 0.95
- A-A-P 1.091


Copying
-------
Copyright (C) 2002-2013 Stuart Rackham. Free use of this software is
granted under the terms of the GNU General Public License version 2
(GPLv2).
